version: "3.3"
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      ports:
       - "9200:9200"
       - "9300:9300"
    kibana:
      image: docker.elastic.co/kibana/kibana:6.3.0
      ports:
       - "5601:5601"
      links:
       - elasticsearch
    logstash:
      build: logstash
      command: logstash -f logstash.conf
      ports:
       - "5043:5043"
       - "5044:5044"
      links:
       - elasticsearch